version: '3'
services:
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    env_file:
      - .env.development
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    env_file:
      - .env.development
    depends_on:
     - "mongodb"
volumes:
  mongo-data:
    driver: local
